FROM ubuntu:focal

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get dist-upgrade -y \
 && apt-get install -y locales sudo

RUN locale-gen en_US.UTF-8 \
 && update-locale LANG=en_US.UTF-8 LANGUAGE=en_US:en
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

RUN adduser --disabled-password --gecos '' docker \
 && adduser docker sudo \
 && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install docker
RUN apt-get install -y \
    ca-certificates curl gnupg lsb-release \
    --no-install-recommends
RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg                                                                                                                                    RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.lRUN apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io \
    --no-install-recommends

RUN apt-get install -y libicu66 liblttng-ust-ctl4 liblttng-ust0 libnuma1 liburcu6

USER docker

# Download the latest runner package

RUN cd /home/docker \
    && mkdir actions-runner && cd actions-runner \
    && curl -o actions-runner-linux-x64-2.290.1.tar.gz \
       -L https://github.com/actions/runner/releases/download/v2.290.1/actions-runner-linux-x64-2.290.1.tar.gz \
    && tar xzf ./actions-runner-linux-x64-2.290.1.tar.gz

RUN cd /home/docker/actions-runner \
    && sudo ./bin/installdependencies.sh \
    && ./config.sh --url https://github.com/heitbaum/libreelec-actions --token sample-token-here < /dev/null

RUN cd /home/docker \
    && echo "sudo chgrp docker /var/run/docker.sock" > runme.sh \
    && echo "cd actions-runner" >> runme.sh \
    && echo "./run.sh" >> runme.sh \
    && chmod 755 runme.sh

# docker run --log-driver none -v /var/run/docker.sock:/var/run/docker.sock -it github-runner:latest runme.sh
# docker run --log-driver none -v /var/run/docker.sock:/var/run/docker.sock -it github-runner:latest bash
# --> this one --> docker run --log-driver none -v /var/run/docker.sock:/var/run/docker.sock -v /var/media/DATA/github-actions:/var/media/DATA/github-actions -it github-runner:latest bash 
