name: libreelec-docker
on:
  # allows to run this workflow manually from the actions tab
  workflow_dispatch:
env:
  TZ: Australia/Melbourne

jobs:
  build_libreelec:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 2
          repository: "LibreELEC/LibreELEC.tv"
          path: "LibreELEC.tv"
      - name: Create LE docker image
        run: |
          ls
          pwd
          cd LibreELEC.tv
          sed -i -e "s/RUN adduser/RUN adduser --uid $(id -u)/" tools/docker/focal/Dockerfile
          docker build --pull -t gh-libreelec tools/docker/focal
      - name: Build LE at docker image
        run: |
          cd LibreELEC.tv
          echo "pwd: $(pwd)"
          echo "id: $(id)"
          echo "whoami: $(whoami)"
          echo "docker images: $(docker images)"
          ln -s /sources .
          ln -s /target .
          echo "ls: $(ls -la)"
          docker run --rm -v /var/media/DATA/github-actions/sources:/sources \
                          -v /var/media/DATA/github-actions/target:/target \
                          -v /var/media/DATA/github-actions/build-root:/build-root \
                          -v `pwd`:/build \
                          -w /build -i \
                          -e CUSTOM_GIT_HASH=ghactions -e PROJECT=Generic \
                          -e ARCH=x86_64 -e ONELOG=no -e LOGCOMBINE=never \
                          -e BUILD_DIR=/build-root \
                          gh-libreelec "make image;make clean"
      - name: 📂 Upload files to server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          protocol: ${{ secrets.ftp_protocol }}
          local-dir: ${{ secrets.ftp_local-dir }}
          server-dir: ${{ secrets.ftp_server-dir }}
