name: libreelec-build-with-docker
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

jobs:
  fetch build and release libreelec:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2
      - name: Initialization running environment
        run: |
          sudo ln -sf /bin/bash /bin/sh 
          sudo mkdir -p /libreelec && sudo -E chmod 777 /libreelec
          sudo mkdir -p /UpReleaseArtifact && sudo -E chmod 777 /UpReleaseArtifact
          sudo mkdir -p /libreelec/myscripts && sudo -E chmod 777 /libreelec/myscripts
          cp scripts/*.sh /libreelec/myscripts
          chmod +x /libreelec/myscripts/*.sh
          /libreelec/myscripts/extern-disk-space.sh
      - name: fetch and build libreelec
        run: |
          cd /libreelec
          /libreelec/myscripts/libreelec-docker.sh    
          tar  cvzf - ./target/ | split -b 2040m - LibreELEC.tv-target.tar.gz.
          mv LibreELEC.tv-target.tar.gz.* /UpReleaseArtifact
          tar  cvzf - ./sources/ | split -b 2040m - LibreELEC.tv-sources.tar.gz.
          mv LibreELEC.tv-sources.tar.gz.* /UpReleaseArtifact          
      - name: clear release    #v1.0.0 is src
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: v1.0.0   #v1.0.0 is src
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: release src    #v1.0.0 is src
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/UpReleaseArtifact/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag:  "v1.0.0"    #v1.0.0 is src

 